project:
  type: website

website:
  title: "inferential.biostatistics"
  favicon: "media/logo.svg"
  page-footer:
    center:
      - text: "Impressum"
        href: impressum.qmd 
      - text: "Legal Notice"
        href: legalnotice.qmd
    
format:
  html:
    toc: false
    page-layout: full
    default-image-extension: svg
    highlight-style: github
    theme: 
      - lumen
      - html/custom.scss

knitr: true

editor: source